config/routes.rb
Rails.application.routes.draw do
  get 'clinics/edit'
  get 'clinics/update'
  devise_for :users
  root to: 'pages#home'
  resources :doctors, controller: :users, only: [:index, :show, :edit, :update] do
    resources :approvals, only: [:edit, :update]
  end
  resources :approvals, only: [:new, :create, :destroy]
  resources :clinics, controller: :clinics, only: [:update]
  get 'dashboard', to: 'users#dashboard', as: :dashboard
end

app/models/approval.rb
class Approval < ApplicationRecord
  belongs_to :specialty
  belongs_to :giver, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_many :approval_fields, dependent: :destroy
  has_many :fields, through: :approval_fields

  validates :headline, :content, presence: true
  #validates :giver,
  #          uniqueness: {
  #            scope: [:receiver],
  #            message: "You have already written a recommendation for this doctor."
  #          }

  include PgSearch::Model
  pg_search_scope :search_approvals_by_keyword,
    against: [:headline, :content],
    using: {
      tsearch: { prefix: true, dictionary: "english" }
    }
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :set_receiver, only: [:edit, :update]
  before_action :set_approval, only: [:edit, :update, :destroy]

  def new
    # errors.add(:name, :blank, message: "You cannot create a recommendation") if current_user == @receiver
    @doctors = policy_scope(User)
    @doctor = search_doctor_by_name(params[:name]) if params[:name].present?
    @approval = Approval.new(giver: current_user)
    @approval.receiver = @doctor
    authorize @approval
  end

  def create
    @approval = Approval.new(approval_params)
    authorize @approval
    @approval.giver = current_user

    @approval.specialty = @approval.receiver.specialties.first

    params[:name] = @approval.receiver.full_name
    if @approval.save
      flash[:notice] = "Recommendation successfully created."
      redirect_to dashboard_path(current_user)
    else
      flash[:alert] = "Error while creating the recommendation."
      render :new

    end
  end

  def edit
  end

  def update
    @approval.update(approval_params)
    if @approval.save
      flash[:notice] = "Recommendation successfully updated."
      redirect_to dashboard_path(current_user)
    else
      flash[:alert] = "Recommendation was not updated yet."
      render :edit
    end
  end

  def destroy
    if @approval.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_path(current_user) }
        format.js
      #  TODO: Create flash: flash[:notice] = "Recommendation successfully deleted."
      end
    end
  end

  private

  def set_receiver
    @receiver = User.find(params[:doctor_id])
    authorize @receiver
  end

  def set_approval
      @approval = Approval.find(params[:id])
      authorize @approval
  end

  def search_doctor_by_name(search_input)
    User.search_by_name(search_input).where(id: @doctors).first
  end


  def approval_params
    params.require(:approval).permit(:content, :receiver_id, :headline, :anonymous, field_ids: [])
  end
end

app/views/approvals/_error_messages.html.erb
<% if @approval.errors.any? %>
  <div class="errors-container">
    <% @approval.errors.messages.each do |message| %>
      <div class="text-card-purple"><%= message[1][0] %></div>
    <% end %>
  </div>
<% end %>

app/views/approvals/_search_bar.html.erb
<div>
  <%= form_tag new_approval_path, method: :get, class: "name-search" do %>
    <div>
      <%= select_tag :name,
            options_from_collection_for_select(
            User.all, "full_name", "full_name_with_title_speciality_clinic",
            params[:name]),
            include_blank: true,
            class: "js-example-basic-single-name input-field",
            id: "doctor_name",
            onchange:"this.form.submit()"
      %>
    </div>
    <div>
      <%= submit_tag "Search", class: "btn-mint" %>
    </div>
  <% end %>
</div>

app/views/approvals/destroy.js.erb
document.querySelector("[data-approval-id='<%= @approval.id %>']")
  .remove();

app/views/approvals/edit.html.erb
<div class="page-container">
  <div class="approval-container">
    <h4>Edit recommendation </h4>
    <p>The recommendee: </p>
    <%= render partial: 'users/doctor_card', object: @receiver, as: :doctor %>
  <div class="approval-form">
    <%= simple_form_for @approval, url: doctor_approval_path(@receiver) do |f| %>
      <%= f.input :headline, placeholder: "Title of your recommendation", class: "approval-headline"%>

      <%= f.label "Fields", :field_ids %>
      <p class="info-text">Please select up to 5 fields you recommend <%= @receiver.full_name_with_title %> for.</p>
      <div class="field-choices">
        <%= f.collection_check_boxes :field_ids,
                                      @receiver.specialties.first.fields,
                                      :id,
                                      :name,
                                      item_wrapper_tag: :div,
                                      item_wrapper_class: "field-choice"  %>
      </div>

      <%= f.input :content, as: :text, placeholder: "Why do you recommend this doctor?"%>

      <div class="anonymous-choice">
        <%= f.input :anonymous, as: :radio_buttons, label: "Do you want to stay anonymous?" %>
      </div>

      <div class="submit-btn-container">
      <%= f.submit "Update", class: "btn-mint"  %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/approvals/new.html.erb
<div class="page-container">
  <div class="approval-container">
    <h4>Write a recommendation </h4>
    <p class="search-tag">Which doctor would you like to recommend?</p>
    <%= render 'search_bar' %>
    <% if !@doctor.nil? %>
      <p>The recommendee: </p>
      <%= render partial: 'users/doctor_card', object: @doctor, as: :doctor %>
      <% @appr = Approval.where(receiver: @doctor, giver: current_user).first %>
      <% if @appr.present? %>
        <div class="text-card-outline-purple d-flex my-4 justify-content-between">You already have a recommendation for this doctor.
          <div>
            <%= link_to image_tag("icons/pen.svg"), edit_doctor_approval_path(@appr.receiver, @appr), style: "margin-left: 16px;" %>
          </div>
        </div>
      <% elsif @doctor == current_user %>
        <div class="text-card-outline-purple d-flex my-4 justify-content-between">
          Sorry. You cannot create a recommendation for yourself.
        </div>
    <% else %>
      <div class="approval-form">
        <%= simple_form_for @approval do |f| %>
          <%= f.input :receiver_id, as: :hidden %>
          <%= f.input :headline, placeholder: "Title of your recommendation", class: "approval-headline"%>
          <%= f.label "Fields", :field_ids %>
          <p class="info-text">Please select up to 5 fields you recommend <%= @approval.receiver.full_name_with_title %> for.</p>
          <div class="field-choices">
            <%= f.collection_check_boxes :field_ids,
                                          @approval.receiver.specialties.first.fields,
                                          :id,
                                          :name,
                                          item_wrapper_tag: :div,
                                          item_wrapper_class: "field-choice"  %>
          </div>

          <%= f.input :content, as: :text, placeholder: "Why do you recommend this doctor?"%>

          <div class="anonymous-choice">
            <%= f.input :anonymous, as: :radio_buttons, label: "Do you want to stay anonymous?" %>
          </div>
          <div class="submit-btn-container">
            <%= f.submit "Recommend", class: "btn-mint"  %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
</div>