config/routes.rb
Rails.application.routes.draw do
  get 'clinics/edit'
  get 'clinics/update'
  devise_for :users
  root to: 'pages#home'
  resources :doctors, controller: :users, only: [:index, :show, :edit, :update] do
    resources :approvals, only: [:edit, :update]
  end
  resources :approvals, only: [:new, :create, :destroy]
  resources :clinics, controller: :clinics, only: [:update]
  get 'dashboard', to: 'users#dashboard', as: :dashboard
end

app/models/user.rb
class User < ApplicationRecord
   mount_uploader :profile_picture, ProfilePictureUploader

  belongs_to :clinic
  has_many :user_specialties
  has_many :specialties, through: :user_specialties
  has_many :user_fields
  has_many :fields, through: :user_fields
  has_many :approvals, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [:first_name, :last_name],
    using: {
      tsearch: { prefix: true }
    }

  def full_name
    "#{self.first_name.capitalize} #{self.last_name.capitalize}"
  end

  def full_name_with_title
    "#{self.title} #{self.first_name.capitalize} #{self.last_name.capitalize}"
  end

  def full_name_with_title_speciality_clinic
    "#{self.title} #{self.first_name.capitalize} #{self.last_name.capitalize} (#{self.specialties.first.name.capitalize}) - #{self.clinic.name}"
  end

  def position_specialty_clinic
    "#{self.position.capitalize} in #{self.specialties.first.name.capitalize} at #{self.clinic.name.capitalize}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :dashboard]
  before_action :set_doctor, only: [:show]
  before_action :set_current_user, only: [:edit, :update, :dashboard]

  # before_filter check if html, js etc
  def index
    @doctors = policy_scope(User)

    if params[:specialty_or_field].present?
      search_by_specialty_or_field(params[:specialty_or_field])
    elsif params[:specialty].present? || params[:field].present? || params[:name].present? || params[:location].present?
      @doctors = search_doctor_by_specialty(params[:specialty]) if params[:specialty].present?
      @doctors = search_doctor_by_field(params[:field]) if params[:field].present?
      @doctors = search_doctor_by_name(params[:name]) if params[:name].present?
      @doctors = search_doctor_by_location if params[:location].present?
    else
      @doctors
    end

    @markers = get_info_for_map_markers(@doctors) if @doctors != []
  end

  def show
    if params[:keyword_search].present? && params[:approval_field].present?
      keyword_results = Approval.where(receiver: @doctor).search_approvals_by_keyword(params[:keyword_search])
      field_results = search_approvals_by_field(params[:approval_field])
      @approvals = [keyword_results, field_results].flatten
      @approvals = @approvals.select { |i| @approvals.count(i) > 1 }.uniq
    elsif params[:keyword_search].present?
      @approvals = Approval.where(receiver: @doctor).search_approvals_by_keyword(params[:keyword_search])
    elsif params[:approval_field].present?
      @approvals = search_approvals_by_field(params[:approval_field])
    else
      results = Approval.all.select { |approval| approval.receiver_id == @doctor.id }
      @approvals = results.sort_by(&:"created_at").reverse
    end
    # months required to show "Nov" instead of '11' on approval cards
    @months = Date::ABBR_MONTHNAMES
    respond_to do |format|
      format.html { render 'users/show' }
      format.js
    end
  end

  def dashboard
    results = Approval.all.select { |approval| approval.giver_id == current_user.id }
    @approvals = results.sort_by(&:"created_at").reverse
    @months = Date::ABBR_MONTHNAMES
    @clinic = current_user.clinic
    @doctor = current_user
    @user = current_user
    authorize @user
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to dashboard_path(@user)
    end
  end

  private

  def search_doctor_by_specialty(search_input)
    # Specialty.where('lower(name) = ?', search_input.downcase).map {|p| p.users }.flatten.uniq
    @specialty = Specialty.joins(:users).where(users: @doctors).search_by_specialty(search_input)
    @doctors = @specialty.map { |p| p.users }.flatten.uniq
  end

  def search_doctor_by_field(search_input)
    if search_input.is_a? Array
      search_input.each do |input|
        @approvals = Approval.where(receiver: @doctors)
        @field = Field.search_by_field(input)
        @doctors = @approvals.joins(:fields).where(fields: {id: @field}).map {|p| p.receiver }.flatten.uniq
        # @doctors = @field.joins(:approvals).where(approvals: { receiver: @doctors }).map {|p| p.users }.flatten.uniq
      end
    else
      @approvals = Approval.where(receiver: @doctors)
      @field = Field.search_by_field(search_input)
      @doctors = @approvals.joins(:fields).where(fields: {id: @field}).map {|p| p.receiver }.flatten.uniq
      # @doctors = @field.joins(:approvals).where(approvals: { receiver: @doctors }).map { |p| p.users }.flatten.uniq
      # Field.joins(:approvals).where('lower(name) = ?', search_input.downcase).map {|p| p.users }.flatten.uniq
    end
    @doctors
  end

  def search_by_specialty_or_field(search_input)
    search_doctor_by_specialty(search_input)
    if @doctors == []
      @doctors = policy_scope(User)
      @doctors = search_doctor_by_field(search_input)
      params[:field] = @field.first.name if @doctors != []
    else
      params[:specialty] = @specialty.first.name
    end
  end

  def search_doctor_by_name(search_input)
    @doctors = User.search_by_name(search_input).where(id: @doctors)
  end

  def search_doctor_by_location
    if params[:location].present?
      @doctors_nearby = search_location
      @doctors = @doctors.select { |doc| @doctors_nearby.include?(doc) }
      return @doctors
    else
      return @doctors
    end
  end

  def search_location
    @clinics = Clinic.near(params[:location], 10)
    @doctors_nearby = @clinics.map { |clinic| clinic.users }
    @doctors_nearby.flatten
  end

  def get_info_for_map_markers(results)
    results.map do |doctor|
      {
        lat: doctor.clinic.latitude,
        lng: doctor.clinic.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { doctor: doctor }),
        image_url: helpers.asset_url('pin-mint.png')
      }
    end
  end

  def search_approvals_by_field(search_input)
    @approvals = Approval.all
    search_input.each do |input|
      @approvals = Approval.joins(:fields).where(receiver: @doctor).where(id: @approvals).where(fields: {name: input}).uniq # how do we prevent SQL injections?
    end
    @approvals
  end

  def set_doctor
    @doctor = User.find(params[:id])
    authorize @doctor
  end

  def set_current_user
    @user = current_user
    authorize @user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :title, :position, :bio, :profile_picture)
  end
end

app/views/users/dashboard/_dashboard_header.html.erb
<div class="dashboard_header">
<div class="dashboard_header-text">
<h2 >Hello <%= current_user.title %> <%= current_user.first_name %> <%= current_user.last_name %></h2>
</div>
<div>
<%= cl_image_tag(current_user.clinic.clinic_picture, height: 300, width: 300, crop: :fill, id: "profile-pic", class: "avatar-square-hospital") %>
</div>
</div>

app/views/users/dashboard/_dashboard_info.html.erb
  <div>
    <%= render 'users/dashboard/dashboard_info_user' %>
  </div>

  <div>
    <%= render 'users/dashboard/dashboard_info_clinic' %>
  </div>

app/views/users/dashboard/_dashboard_info_clinic.html.erb
<div class="dashboard-profile-summary info-section">
  <% percentage = 0 %>
  <% progress_color = "#42433e" %>
  <% font_color = "#42433E" %>
<!-- This calculates the percentage depending the amount of data saved in the profile -->
  <% if !current_user.clinic.name.empty? %>
  <% percentage += 11 %>
  <% end %>

  <% if current_user.profile_picture != nil %>
  <% percentage += 12 %>
  <% end %>

  <% if !current_user.clinic.address.empty? %>
  <% percentage += 12 %>
  <% end %>

  <% if !current_user.clinic.phone_number.empty? %>
  <% percentage += 13 %>
  <% end %>

  <% if !current_user.clinic.website.empty? %>
  <% percentage += 13 %>
  <% end %>

  <% if !current_user.clinic.email.empty? %>
  <% percentage += 13 %>
  <% end %>

  <% if !current_user.clinic.consultation_times.empty? %>
  <% percentage += 13 %>
  <% end %>

  <% if !current_user.clinic.description.empty? %>
  <% percentage += 13 %>
  <% end %>
<!-- This calculates the color of the progress bar's background depending on the percentge -->
  <% if percentage >= 0 && percentage <= 30 %>
  <% progress_color = "#FD1015" %>
  <% elsif percentage > 30 && percentage <= 60 %>
  <% progress_color = "#E67E22" %>
  <% elsif percentage > 60 && percentage <= 99 %>
  <% progress_color = "#fff538" %>
  <% else %>
  <% percentage = 100 %>
  <% progress_color = "#6fbcb4" %>
  <% font_color = "#FFFFFF" %>
  <% end %>

<div>
  <h4>Clinic information</h4>
  <div class="progress position-relative" style="height: 25px; width: 50%; margin: 0 auto; margin-top: 15px; font-size: 0.95rem; color: <%= font_color %>;">
    <div class="progress-bar" role="progressbar" style="background: <%= progress_color %>; width: <%= percentage %>%" aria-valuenow="<%= percentage %>" aria-valuemin="0" aria-valuemax="100"></div>
    <div class="justify-content-center d-flex position-absolute w-100"><%= percentage %>% Completed</div>
  </div>
  <div style="padding-top: 36px;">
  <% if current_user.clinic.clinic_picture != nil %>
    <%= cl_image_tag current_user.clinic.clinic_picture, class: "avatar-square" %>
  <% end %>
  </div>

    <div class="dashboard-profile-summary-data info-section" id="current-clinic-data">
      <div>
      <p><strong>Name:</strong>
        <% if !current_user.clinic.name.empty? %>
        <%= current_user.clinic.name %>
        <% else %>
        <%= "No name provided." %>
        <% end %>
      </p>
      <p><strong>Address:</strong>
        <% if !current_user.clinic.address.empty? %>
        <%= current_user.clinic.address %>
        <% else %>
        <%= "No address provided." %>
        <% end %>
      </p>
      <p><strong>Phone:</strong>
        <% if !current_user.clinic.phone_number.empty? %>
        <%= current_user.clinic.phone_number %>
        <% else %>
        <%= "No phone provided." %>
        <% end %>
      </p>
      <p><strong>Website:</strong>
        <% if !current_user.clinic.website.empty? %>
        <%= current_user.clinic.website %>
        <% else %>
        <%= "No website provided." %>
        <% end %>
      </p>
      <p><strong>Email:</strong>
        <% if !current_user.clinic.email.empty? %>
        <%= current_user.clinic.email %>
        <% else %>
        <%= "No email provided." %>
        <% end %>
      </p>
      <p><strong>Consultation Times:</strong>
        <% if !current_user.clinic.consultation_times.empty? %>
        <%= current_user.clinic.consultation_times %>
        <% else %>
        <%= "No consultation times provided." %>
        <% end %>
      </p>
      <p><strong>Description:</strong>
        <% if !current_user.clinic.description.empty? %>
        <%= current_user.clinic.description %>
        <% else %>
        <%= "No description provided." %>
        <% end %>
      </p>
      </div>
    </div>
      <div class="edit-btn">
        <button id="edit-clinic-btn" class="btn-mint">Edit</button>
      </div>
  </div>

    <div id="edit-clinic" class="hide">
      <%= form_for @clinic, url: clinic_path(@clinic) do |f| %> <!-- , url: { action: "update" } -->
        <br><strong>Clinic Picture</strong><br>
        <%= f.file_field :clinic_picture %>
        <%= f.hidden_field :clinic_picture_cache, as: :hidden %> <br>
        <strong>Name:</strong><br>
        <%= text_field_tag :name,
          params[:name] = @clinic.name,
          class: "input-field edit-field"
          %>
        <strong>Address:</strong><br>
        <%= text_field_tag :address,
          params[:address] = @clinic.address,
          class: "input-field edit-field"
          %>
        <strong>Phone:</strong><br>
        <%= text_field_tag :phone_number,
          params[:phone_number] = @clinic.phone_number,
          class: "input-field edit-field"
          %>
        <strong>Website:</strong><br>
        <%= text_field_tag :website,
          params[:website] = @clinic.website,
          class: "input-field edit-field"
          %>
        <strong>Email:</strong><br>
        <%= text_field_tag :email,
          params[:email] = @clinic.email,
          class: "input-field edit-field"
          %>
        <strong>Consultation Times:</strong><br>
        <%= text_field_tag :consultation_times,
          params[:consultation_times] = @clinic.consultation_times,
          class: "input-field edit-field"
          %>
        <strong>Description:</strong><br>
        <%= text_area_tag :description,
          params[:description] = @clinic.description,
          class: "input-field edit-field"
          %>
          <br>
        <div class="edit-btn">
          <%= submit_tag "Update", id: "save-clinic-btn", class: "btn-mint" %>
        </div>
      <% end %>
    </div>
</div>

app/views/users/dashboard/_dashboard_info_quota.html.erb
<div class="dashboard-profile-summary">
  <% percentage = 0 %>
  <% total_allowed = Specialty.all.count * 4 %>
  <% specialty_allowed = 4 %>
  <% global_count = (2*100)/total_allowed %>
  <% specialty_count = (3*100)/specialty_allowed %>
  <% progress_color_g = "#42433e" %>
  <% progress_color_s = "#42433e" %>
  <% font_color_g = "#42433E" %>
  <% font_color_s = "#42433E" %>
<!-- This calculates the remaining referrals -->

<!-- This calculates the color of "Total remaining available referrals" progress bar's background depending on the remaining referrals -->
  <% if global_count >= 0 && global_count <= 30 %>
  <% progress_color_g = "#6fbcb4" %>
  <% elsif global_count > 30 && global_count <= 60 %>
  <% progress_color_g = "#fff538" %>
  <% elsif global_count > 60 && global_count <= 99 %>
  <% progress_color_g = "#E67E22" %>
  <% else %>
  <% global_count = (total_allowed*100)/total_allowed %>
  <% progress_color_g = "#FD1015" %>
  <% end %>
<!-- This calculates the color of "Remaining available referrals by specialty" progress bars' background depending on the remaining referrals -->
  <% if specialty_count >= 0 && specialty_count <= 30 %>
  <% progress_color_s = "#6fbcb4" %>
  <% elsif specialty_count > 30 && specialty_count <= 60 %>
  <% progress_color_s = "#fff538" %>
  <% elsif specialty_count > 60 && specialty_count <= 99 %>
  <% progress_color_s = "#E67E22" %>
  <% else %>
  <% specialty_count = (specialty_allowed*100)/specialty_allowed %>
  <% progress_color_s = "#FD1015" %>
  <% end %>

  <h4>Remaining Quota</h4>

  <p>Total remaining available referrals</p>
  <div class="progress position-relative" style="height: 25px; width: 50%; margin: 15px auto; font-size: 0.95rem; color: <%= font_color_g %>;">
    <div class="progress-bar" role="progressbar" style="background: <%= progress_color_g %>; width: <%= global_count %>%" aria-valuenow="<%= global_count %>" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="justify-content-center d-flex position-absolute w-100"><%= (global_count*total_allowed)/100 %> of <%= total_allowed %></div>
  </div>

  <p>Remaining available referrals by specialty</p>

  <% Specialty.all.each do |specialty| %>
  <%= specialty.name.capitalize %>
  <div class="progress position-relative" style="height: 25px; width: 50%; margin: 15px auto; font-size: 0.95rem; color: <%= font_color_s %>;">
    <div class="progress-bar" role="progressbar" style="background: <%= progress_color_s %>; width: <%= specialty_count %>%" aria-valuenow="<%= specialty_count %>" aria-valuemin="0" aria-valuemax="100"></div>
    <div class="justify-content-center d-flex position-absolute w-100"><%= (specialty_count*specialty_allowed)/100 %> of <%= specialty_allowed %></div>
  </div>
  <% end %>
</div>

app/views/users/dashboard/_dashboard_info_user.html.erb
<div class="dashboard-profile-summary info-section">
  <% percentage = 0 %>
  <% progress_color = "#42433e" %>
  <% font_color = "#42433E" %>
<!-- This calculates the percentage depending the amount of data saved in the profile -->
  <% if !current_user.first_name.empty? %>
  <% percentage += 15 %>
  <% end %>

  <% if !current_user.last_name.empty? %>
  <% percentage += 15 %>
  <% end %>

  <% if !current_user.email.empty? %>
  <% percentage += 14 %>
  <% end %>

  <% if current_user.profile_picture != nil %>
  <% percentage += 14 %>
  <% end %>

  <% if !current_user.bio.empty? %>
  <% percentage += 14 %>
  <% end %>

  <% if !current_user.position.empty? %>
  <% percentage += 14 %>
  <% end %>

  <% if !current_user.title.empty? %>
  <% percentage += 14 %>
  <% end %>
<!-- This calculates the color of the progress bar's background depending on the percentge -->
  <% if percentage >= 0 && percentage <= 30 %>
  <% progress_color = "#FD1015" %>
  <% elsif percentage > 30 && percentage <= 60 %>
  <% progress_color = "#E67E22" %>
  <% elsif percentage > 60 && percentage <= 99 %>
  <% progress_color = "#fff538" %>
  <% else %>
  <% percentage = 100 %>
  <% progress_color = "#6fbcb4" %>
  <% font_color = "#FFFFFF" %>
  <% end %>

<div>
  <h4>Personal information</h4>
  <div class="progress position-relative" style="height: 25px; width: 50%; margin: 0 auto; margin-top: 15px; font-size: 0.95rem; color: <%= font_color %>;">
    <div class="progress-bar" role="progressbar" style="background: <%= progress_color %>; width: <%= percentage %>%" aria-valuenow="<%= percentage %>" aria-valuemin="0" aria-valuemax="100"></div>
    <div class="justify-content-center d-flex position-absolute w-100"><%= percentage %>% Completed</div>
  </div>
  <div style="padding-top: 36px;">
  <% if current_user.profile_picture != nil %>
    <%= cl_image_tag current_user.profile_picture, class: "avatar-square" %>
  <% end %>
  </div>
    <div class="dashboard-profile-summary-data info-section" id="current-profile-data">
      <div>
      <p><strong>Name:</strong>
        <%=current_user.first_name + " " + current_user.last_name%>
        </p>
      <p><strong>Title:</strong>
        <% if !current_user.title.empty? %>
        <%= current_user.title %>
        <% else %>
        <%= "No title provided." %>
        <% end %>
      </p>
      <p><strong>Position:</strong>
        <% if !current_user.position.empty? %>
        <%= current_user.position %>
        <% else %>
        <%= "No position provided." %>
        <% end %>
      </p>
      <p><strong>Email:</strong>
        <% if !current_user.email.empty? %>
        <%= current_user.email %>
        <% else %>
        <%= "No email provided." %>
        <% end %>
      </p>
      <p><strong>Bio:</strong>
        <% if !current_user.bio.empty? %>
        <%= current_user.bio %>
        <% else %>
        <%= "No bio provided." %>
        <% end %>
      </p>
      </div>
      <div class="edit-btn">
        <button id="edit-profile-btn" class="btn-mint">Edit</button>
      </div>
    </div>
  </div>

    <div id="edit-profile" class="hide">
      <%#= form_for @user, url: doctor_path(@user), html: { multipart: true } do |f| %>
      <%= render template: 'devise/registrations/edit' %>
    </div>
</div>

app/views/users/dashboard/_dashboard_landing.html.erb
<div>
  <ul class="nav nav-tabs" style="height: 45px; margin-top: 0px;">
    <li class="nav-item">
      <a class="nav-link profile-tab active" href="#recommendations" role="tab" data-toggle="tab">Recommendations</a>
    </li>
    <li class="nav-item">
      <a class="nav-link profile-tab" href="#profile" role="tab" data-toggle="tab">Profile Info</a>
    </li>
  </ul>
  <div class="tab-content">
    <div role='tabpanel' class= "tab-pane active fade show" id="recommendations">
      <%= render 'users/dashboard/dashboard_reviews' %>
    </div>
    <div role='tabpanel' class= "tab-pane fade" id="profile">
      <div class="dashboard-info-layout"><%= render 'users/dashboard/dashboard_info' %></div>
    </div>
  </div>
</div>

app/views/users/dashboard/_dashboard_reviews.html.erb
<div>
  <div class="tab-organisation-box">
    <div></div>
    <div>
      <ul class="nav nav-tabs" style="height: 50px; margin-top: 0px;">
        <li class="nav-item">
          <a id="dash-tab-review" class="nav-link profile-tab active" href="#given" role="tab" data-toggle="tab">Given</a>
        </li>
        <li class="nav-item">
          <a id="dash-tab-review" class="nav-link profile-tab" href="#received" role="tab" data-toggle="tab">Received</a>
        </li>
      </ul>

    </div>
  </div>

  <div class="tab-content">
    <div role='tabpanel' class= "tab-pane active fade show" id="given">
      <div class="dashboard-body-layout"><%= render 'users/dashboard/dashboard_reviews_given' %></div>
    </div>
    <div role='tabpanel' class= "tab-pane fade" id="received">
      <div class="dashboard-body-layout"><%= render 'users/dashboard/dashboard_reviews_received' %></div>
    </div>
  </div>
</div>

app/views/users/dashboard/_dashboard_reviews_given.html.erb
<!-- Do not delete outer div -->
<div>
  <%= render 'users/dashboard/dashboard_reviews_given_quota' %>
</div>

<div>
  <% @approvals.each do |approval| %>
  <!-- Info box on top of recommendations -->
    <div data-approval-id="<%= approval.id %>">
      <div class="approval-info-box d-flex align-items-center">
        <div>
          <% recommendee = approval.receiver %>
          <%= link_to doctor_path(recommendee) do  %>
            <%= cl_image_tag recommendee.profile_picture,
              height: 50,
              width: 50,
              crop: :fill,
              class: "avatar-medium"
            %>
          <% end %>
        </div>
        <div>
              <p style= "padding: 0 16px; margin-bottom: 0;">You recommended <strong> <%= link_to "#{recommendee.title} #{recommendee.first_name} #{recommendee.last_name}", doctor_path(recommendee), style: "text-decoration: none; color: rgb(66, 67, 62);" %> </strong> at <%= recommendee.clinic.name %></p>
        </div>
        <div>
          <%= link_to image_tag("icons/pen.svg"), edit_doctor_approval_path(approval.receiver, approval), style: "margin-left: 16px;" %>
        </div>
        <div>
          <%= link_to image_tag("icons/trash.svg"), approval_path(approval), method: :delete, remote: true, data: {confirm: "Are you sure?"}, style: "margin-left: 16px;" %>
        </div>
      </div>
      <div>
        <%= render partial: 'users/profile_page/approval_card/approval_card', locals: { approval: approval} %>
      </div>
    </div>

  <% end %>
</div>

app/views/users/dashboard/_dashboard_reviews_given_quota.html.erb
<div class="dashboard-profile-summary">
  <% global_allowed = Specialty.all.count * 4 %>
  <% global_count = 0 %>
  <% specialty_allowed = 4 %>
  <% specialty_count = 0 %>
  <% progress_color_g = "#80C4BD" %>
  <% progress_color_s = "#80C4BD" %>
  <% font_color_g = "#42433E" %>
  <% font_color_s = "#ffffff" %>
  <% specialty_order_hash = Hash.new %>

  <!-- Count all the referals given-->
  <% Specialty.all.each do |specialty| %>
  <% global_count += Approval.where(giver: current_user).where(specialty: specialty).count %>
  <% end %>
  <% global_count_percentage = (global_count*100)/global_allowed %>

  <!-- This calculates the color of "Total remaining available referrals" progress bar's background depending on the remaining referrals -->
  <% if global_count_percentage >= 0 && global_count_percentage <= 30 %>
  <% progress_color_g = "#D3D0FF" %>
  <% elsif global_count_percentage > 30 && global_count_percentage <= 60 %>
  <% progress_color_g = "#A59FFF" %>
  <% elsif global_count_percentage > 60 && global_count_percentage <= 99 %>
  <% progress_color_g = "#6C63FF" %>
  <% else %>
  <% global_count_percentage = 100 %>
  <% progress_color_g = "#80C4BD" %>
  <% end %>

  <h4>Remaining Quota</h4>
  <div class="dashboard-profile-summary" style="border: none; padding-bottom: 0;">
  <p>Given recommendations</p>
  <div class="progress position-relative" style="height: 25px; width: 150px; margin: 15px auto; font-size: 0.95rem; color: <%= font_color_g %>;">
    <div class="progress-bar" role="progressbar" style="background: <%= progress_color_g %>; width: <%= global_count_percentage %>%" aria-valuenow="<%= global_count %>" aria-valuemin="0" aria-valuemax="100"></div>
    <div class="justify-content-center d-flex position-absolute w-100"><%= global_count %> of <%= global_allowed %></div>
  </div>
  </div>

  <div class="dashboard-profile-summary" style="border: none; padding: 24px; text-align: start;">
    <p>Given recommendations by specialty</p>
  </div>

  <% Specialty.all.each do |specialty| %>
    <% specialty_count = Approval.where(giver: current_user).where(specialty: specialty).count %>
    <% specialty_order_hash[specialty.name.capitalize] = specialty_count %>
  <% end %>
  <% specialty_order_hash = specialty_order_hash.sort_by {|k, v| -v} %>

  <div>
    <% specialty_order_hash.each do |specialty, count| %>

      <% specialty_count_percentage = (count*100)/specialty_allowed %>
      <% font_color_s = "#42433E" %>
      <% if specialty_count_percentage >= 0 && specialty_count_percentage <= 30 %>
      <% progress_color_s = "#D3D0FF" %>
      <% elsif specialty_count_percentage > 30 && specialty_count_percentage <= 60 %>
      <% progress_color_s = "#A59FFF" %>
      <% elsif specialty_count_percentage > 60 && specialty_count_percentage <= 99 %>
      <% progress_color_s = "#6C63FF" %>
      <% font_color_s = "#ffffff" %>
      <% else %>
      <% specialty_count_percentage = 100 %>
      <% progress_color_s = "#80C4BD" %>
      <% font_color_s = "#ffffff" %>
      <% end %>

      <div class="dashboard-profile-summary gridded" style="border: none">
        <div>
          <div><%= specialty %></div>
        </div>
        <div>
          <div class= "d-flex align-items-center" style="height: 30px;">
            <div class="progress position-relative" style="height: 22px; width: 100%; margin: 15px auto; font-size: 0.95rem; color: <%= font_color_s %>;">
              <div class="progress-bar" role="progressbar" style="background: <%= progress_color_s %>; width: <%= specialty_count_percentage %>%" aria-valuenow="<%= specialty_count_percentage %>" aria-valuemin="0" aria-valuemax="100"></div>
              <div class="justify-content-center d-flex position-absolute w-100"><%= count %> of <%= specialty_allowed %></div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/dashboard/_dashboard_reviews_received.html.erb
<div>
<%= render 'users/dashboard/dashboard_reviews_received_quota' %>
</div>

<div>
  <% results = Approval.all.select { |approval| approval.receiver_id == current_user.id } %>
  <% @approvals = results.sort_by(&:"created_at").reverse %>
  <%= render 'users/profile_page/profile_approvalcards_list' %>
</div>