config/routes.rb
Rails.application.routes.draw do
  get 'clinics/edit'
  get 'clinics/update'
  devise_for :users
  root to: 'pages#home'
  resources :doctors, controller: :users, only: [:index, :show, :edit, :update] do
    resources :approvals, only: [:edit, :update]
  end
  resources :approvals, only: [:new, :create, :destroy]
  resources :clinics, controller: :clinics, only: [:update]
  get 'dashboard', to: 'users#dashboard', as: :dashboard
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<!-- Footer -->
    <footer class="pt-5 pb-4" id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
            <h5 class="mb-4 font-weight-bold">ABOUT US</h5>
            <p class="mb-4">Launched by a team of doctors and engineers, DocRef connects patients with the doctor they need.</p>
            <ul class="f-address">
<!--               <li>
                <div class="row">
                  <div class="col-1"><i class="fas fa-map-marker"></i></div>
                  <div class="col-10">
                    <h6 class="font-weight-bold mb-0">Address:</h6>
                    <p>Berlin</p>
                  </div>
                </div>
              </li> -->
              <li>
                <div class="row">
                  <div class="col-1"><i class="far fa-envelope"></i></div>
                  <div class="col-10">
                    <h6 class="font-weight-bold mb-0">Want to get involved?</h6>
                    <p><a href="#">hello@docref.de</a></p>
                  </div>
                </div>
              </li>
              <!-- <li>
                <div class="row">
                  <div class="col-1"><i class="fas fa-phone-volume"></i></div>
                  <div class="col-10">
                    <h6 class="font-weight-bold mb-0">Phone:</h6>
                    <p><a href="#">+XX (0) XX XX-XXXX-XXXX</a></p>
                  </div>
                </div>
              </li> -->
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
            <h5 class="mb-4 font-weight-bold">FRESH TWEETS</h5>
            <ul class="f-address">
              <li>
                <div class="row">
                  <div class="col-1"><i class="fab fa-twitter"></i></div>
                  <div class="col-10">
                    <p class="mb-0">@docrefgermany</p>
                    <p class="mb-0">DocRef pitching today in Berlin!</p>
                    <label>7 Days Ago</label>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="col-1"><i class="fab fa-twitter"></i></div>
                  <div class="col-10">
                    <p class="mb-0">@docrefgermany</p>
                    <p class="mb-0">Interested in our work? Join our team (hello@docref.de) </p>
                    <label>10 Days Ago</label>
                  </div>
                </div>
              </li>
             <!--  <li>
                <div class="row">
                  <div class="col-1"><i class="fab fa-twitter"></i></div>
                  <div class="col-10">
                    <p class="mb-0"><a href="#">@docrefgermany </a> You like the idea? Get in touch with us!</p>
                    <label>2 Hours Ago</label>
                  </div>
                </div>
              </li> -->
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
            <h5 class="mb-4 font-weight-bold">LATEST UPDATES</h5>
            <ul class="recent-post">
              <li>
                <label class="mr-3">6 <br><span>OCT</span></label>
                <span>DocRef pitching in Berlin Mitte!</span>
              </li>
              <li>
                <label class="mr-3">15 <br><span>SEP</span></label>
                <span>DocRef beta 2.0 launched!</span>
              </li>
             <!--  <li>
                <label class="mr-3">5 <br><span>DEC</span></label>
                <span>DocRef Info Session at Berlin Charité Mitte</span>
              </li> -->
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
            <h5 class="mb-4 font-weight-bold">CONNECT WITH US</h5>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Your Email Address">
                <span class="input-group-addon" id="basic-addon2"><i class="fas fa-check"></i></span>
            </div>
            <ul class="social-pet mt-4">
              <li><a href="https://de-de.facebook.com/" title="facebook"><i class="fab fa-facebook-f"></i></a></li>
              <li><a href="https://twitter.com/" title="twitter"><i class="fab fa-twitter"></i></a></li>
              <li><a href="https://accounts.google.com/ServiceLogin/signinchooser?passive=1209600&continue=https%3A%2F%2Faccounts.google.com%2F&followup=https%3A%2F%2Faccounts.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin" title="google-plus"><i class="fab fa-google-plus-g"></i></a></li>
              <li><a href="https://www.instagram.com/" title="instagram"><i class="fab fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- Copyright -->
    <section class="copyright">
      <div class="container">
        <div class="row">
          <div class="col-md-12 ">
            <div class="text-center">
              &copy; 2020 DocRef | Mike Yousef | All Rights Reserved.
            </div>
          </div>
        </div>
      </div>
    </section>

app/views/shared/_icon_check.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 48 48"><title>ic_check_circle_48px</title>
  <g fill="rgb(111, 188, 180)">
    <path d="M24 4C12.95 4 4 12.95 4 24c0 11.04 8.95 20 20 20 11.04 0 20-8.96 20-20 0-11.05-8.96-20-20-20zm-4 30L10 24l2.83-2.83L20 28.34l15.17-15.17L38 16 20 34z"></path>
  </g>
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="tag-container">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "docreflogo.png" %>
    <% end %>
    <div id="text-logo"><h2>DocRef</h2></div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to "Recommend", new_approval_path, class: "btn-mint outline" %>
        <%= link_to "Search", doctors_path, class: "btn-mint outline" %>
      <li class="nav-item active" style="margin: 0px;">
        <%= link_to "#{current_user.title} #{current_user.first_name} #{current_user.last_name}", doctor_path(current_user), class: "nav-link text_mint" %>
      </li>
      <li class="nav-item dropdown">
        <%= cl_image_tag current_user.profile_picture,
            height: 100,
            width: 100,
            crop: :fill,
            id: "navbarDropdown",
            class: "avatar dropdown-toggle",
            data: { toggle: "dropdown" },
            'aria-haspopup': true,
            'aria-expanded': false
        %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li>
        <%= link_to "Search", doctors_path, class: "btn-mint outline", style: "width: 104px;" %>
        <%= link_to "For doctors", new_user_session_path, class: "btn-mint outline" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div>
  <%= form_tag doctors_path, method: :get, class: "two-field-search-container" do %>
    <%= text_field_tag :specialty_or_field,
      params[:specialty_or_field],
      class: "input-field",
      placeholder: "cardiologist"
    %>
    <div class="location_input">
      <%= search_field_tag :location,
        params[:location],
        class: "input-field address-input",
        placeholder: "Berlin Mitte"
      %>
    </div>
    <%= submit_tag "Search", class: "btn-mint" %>
  <% end %>
</div>

app/views/shared/_temp.html.erb
<div class="page-container">
  <h1>Headline</h1>
  <h3>Page Title</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil provident officiis harum magni corrupti debitis error, assumenda, neque cum obcaecati laborum expedita quibusdam quod itaque possimus nesciunt vitae aliquam! Similique.</p>
  <p class="">Lorem ipsum dolor sit amet, <span class="highlighted">consectetur adipisicing elit.</span> Nihil provident officiis harum magni corrupti debitis error, assumenda, neque cum obcaecati laborum expedita quibusdam quod itaque possimus nesciunt vitae aliquam! Similique.</p>
  <p class="light-blue">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil provident officiis harum magni corrupti debitis error, assumenda, neque cum obcaecati laborum expedita quibusdam quod itaque possimus nesciunt vitae aliquam! Similique.</p>
  <div class="text-card-mint">
    <h4>Lorem ipsum</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel.</p>
  </div>
  <div class="text-card-purple">
    <h4>Lorem ipsum</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel.</p>
  </div>
  <div class="text-card-outline-mint">
    <h4>Lorem ipsum</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel.</p>
  </div>
  <div class="text-card-outline-purple">
    <h4>Lorem ipsum</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel.</p>
  </div>

  <div class="card-doc">
    <div>
      <h4>Dr. Tobias Teich</h4>
      <div>Berlin</div>
      <div>Cardiologist</div>
      <div>Referred by <strong>2</strong> doctors</div>
    </div>
    <%= image_tag "profile.png", alt: "profile_picture", class:"avatar-square" %>
    <p class="desc-doc">"Lorem ipsum dolor sit amet, consectetur adipisicing elit."</p>
    <a class= "btn-outline" href="#">Profile</a>
  </div>

  <div class="card-doc">
    <div>
      <h4>Dr. Tobias Teich</h4>
      <div>Berlin</div>
      <div>Cardiologist</div>
      <div>Referred by <strong>2</strong> doctors</div>
    </div>
    <%= image_tag "profile.png", alt: "profile_picture", class:"avatar-square" %>
    <div></div>
    <a class= "btn-outline" href="#">Profile</a>
  </div>

  <div class="card-approval">
    <div class="approval-header">
      <h4>Super doc</h4>
      <div>25. November 2019</div>
    </div>
    <div class="tag-container">
      <div class="tag">heart disease</div>
      <div class="tag">high blood pressure</div>
      <div class="tag-outline">another condition</div>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel.</p>
  </div>

  <div class="card-approval">
    <div class="approval-header">
      <h4>Super doc</h4>
      <div>25. November 2019</div>
    </div>
    <div class="tag-container">
      <div class="tag">heart disease</div>
      <div class="tag">high blood pressure</div>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto eos ea, beatae ipsam est velit. Doloremque possimus dicta nisi, accusamus officia modi non sequi aperiam, nostrum architecto blanditiis cum vero.</p>
  </div>

  <div class="card-approval-mint">
    <div class="approval-header">
      <h4>Super doc</h4>
      <div>25. November 2019</div>
    </div>
    <div class="tag-container">
      <div class="tag">heart disease</div>
      <div class="tag">high blood pressure</div>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate nihil sit neque praesentium inventore quae recusandae alias, incidunt tempore, quas iste voluptatum facere tempora totam dolores modi. Nulla laborum, vel. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto eos ea, beatae ipsam est velit. Doloremque possimus dicta nisi, accusamus officia modi non sequi aperiam, nostrum architecto blanditiis cum vero.</p>
  </div>


  <div class="btn-container">
    <a class= "btn-mint" href="#">Click Me</a>
    <a class= "btn-outline" href="#">Click Me</a>
  </div>
  <div class="btn-container">
    <a class= "btn-purple" href="#">Click Me</a>
    <a class= "btn-light-purple" href="#">Click Me</a>
    <a class= "btn-outline-purple" href="#">Click Me</a>
  </div>

  <div class="search-container">
    <input class="input-field" type="text">
    <a class= "btn-mint" href="#">Search</a>
  </div>
  <div class="two-search-container">
    <input class="input-field" type="text" placeholder="Cardiologist">
    <input class="input-field" type="text" placeholder="Berlin">
    <a class= "btn-mint" href="#">Search</a>
  </div>

  <form action="#" class="form-recommendation">
    <p><strong>Recommend doctor XY</strong></p>
        <!-- <div>
        <label for="speciality"><strong>Select the speciality</strong></label>
      </div> -->
      <select name="" id="speciality" class="select-speciality">
        <option value="Cardiologist">Cardiologist</option>
        <option value="Dentist">Dentist</option>
      </select>
      <p><strong>Select the conditions doctor xy is especially good in</strong></p>
      <div class="checkbox-container">
        <div>
          <input type="checkbox" name="conditon" id="c1" value="c1">
          <label for="c1">Condition 1</label>
        </div>
        <div>
          <input type="checkbox" name="conditon" id="c2" value="c1">
          <label for="c2">Condition 2</label>
        </div>
        <div>
          <input type="checkbox" name="conditon" id="c3" value="c1">
          <label for="c3">Condition 3</label>
        </div>
        <div>
          <input type="checkbox" name="conditon" id="c4" value="c1">
          <label for="c4">Condition 4</label>
        </div>
        <div>
          <input type="checkbox" name="conditon" id="c5" value="c1">
          <label for="c5">Condition 5</label>
        </div>
        <div>
          <input type="checkbox" name="conditon" id="c6" value="c1">
          <label for="c6">Condition 6</label>
        </div>
      </div>
      <input id="headline"type="text" placeholder="Title of recommendation" class="input-headline">
      <div>
        <textarea placeholder="Why do you recommend the doctor?"></textarea>
      </div>
      <div>
        <button type="submit" class="btn-mint">Submit</button>
      </div>
    </form>
  </div>